modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mobcapture"
version = "${version}"
displayName = "MobCapture"
authors = "KaamaDE"
description = '''
MobCapture introduces the Capturing enchantment, allowing players to collect mob spawn eggs by defeating creatures with enchanted swords. The chance to obtain a spawn egg increases with higher enchantment levels, making mob farming and collection easier and more rewarding. Boss mobs are excluded to maintain game balance. MobCapture supports both Fabric and NeoForge platforms and is available in multiple languages for a global Minecraft experience.
'''
logoFile = "assets/mobcapture/icon.png"

[[dependencies.mobcapture]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobcapture]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobcapture]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mobcapture.mixins.json"
